phpfpm:
  scale: 2
  upgrade_strategy:
    start_first: true
datacontainer:
  scale: 2
  upgrade_strategy:
    start_first: true
marmot-lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
  upgrade_strategy:
    start_first: true
nginx-1:
  scale: 2
  upgrade_strategy:
    start_first: true
